---
total_semantic_labels: 80
dynamic_labels: []
invalid_labels: []
object_labels: [39, 41, 42, 43, 44, 45, 56, 57, 60, 62, 63, 64, 65, 66, 67, 68, 75, 76]
structure_labels: [0]
surface_places_labels: []
label_names:
  - { label: 0, name: background }
  - { label: 1, name: 1 }
  - { label: 2, name: 2 }
  - { label: 3, name: 3 }
  - { label: 4, name: 4 }
  - { label: 5, name: 5 }
  - { label: 6, name: 6 }
  - { label: 7, name: 7 }
  - { label: 8, name: 8 }
  - { label: 9, name: 9 }
  - { label: 10, name: 10 }
  - { label: 11, name: 11 }
  - { label: 12, name: 12 }
  - { label: 13, name: 13 }
  - { label: 14, name: 14 }
  - { label: 15, name: 15 }
  - { label: 16, name: 16 }
  - { label: 17, name: 17 }
  - { label: 18, name: 18 }
  - { label: 19, name: 19 }
  - { label: 20, name: 20 }
  - { label: 21, name: 21 }
  - { label: 22, name: 22 }
  - { label: 23, name: 23 }
  - { label: 24, name: 24 }
  - { label: 25, name: 25 }
  - { label: 26, name: 26 }
  - { label: 27, name: 27 }
  - { label: 28, name: 28 }
  - { label: 29, name: 29 }
  - { label: 30, name: 30 }
  - { label: 31, name: 31 }
  - { label: 32, name: 32 }
  - { label: 33, name: 33 }
  - { label: 34, name: 34 }
  - { label: 35, name: 35 }
  - { label: 36, name: 36 }
  - { label: 37, name: 37 }
  - { label: 38, name: 38 }
  - { label: 39, name: 39 }
  - { label: 40, name: 40 }
  - { label: 41, name: 41 }
  - { label: 42, name: 42 }
  - { label: 43, name: 43 }
  - { label: 44, name: 44 }
  - { label: 45, name: 45 }
  - { label: 46, name: 46 }
  - { label: 47, name: 47 }
  - { label: 48, name: 48 }
  - { label: 49, name: 49 }
  - { label: 50, name: 50 }
  - { label: 51, name: 51 }
  - { label: 52, name: 52 }
  - { label: 53, name: 53 }
  - { label: 54, name: 54 }
  - { label: 55, name: 55 }
  - { label: 56, name: 56 }
  - { label: 57, name: 57 }
  - { label: 58, name: 58 }
  - { label: 59, name: 59 }
  - { label: 60, name: 60 }
  - { label: 61, name: 61 }
  - { label: 62, name: 62 }
  - { label: 63, name: 63 }
  - { label: 64, name: 64 }
  - { label: 65, name: 65 }
  - { label: 66, name: 66 }
  - { label: 67, name: 67 }
  - { label: 68, name: 68 }
  - { label: 69, name: 69 }
  - { label: 70, name: 70 }
  - { label: 71, name: 71 }
  - { label: 72, name: 72 }
  - { label: 73, name: 73 }
  - { label: 74, name: 74 }
  - { label: 75, name: 75 }
  - { label: 76, name: 76 }
  - { label: 77, name: 77 }
  - { label: 78, name: 78 }
  - { label: 79, name: 79 }
